import React from "react";

const ListSection = ({ title, items, icon }) => (
  <div className="ai-list-section">
    <h3>{icon} {title}</h3>
    {items && items.length > 0 ? (
      <ul className="clean-list">
        {items.map((item, index) => <li key={index}>{item}</li>)}
      </ul>
    ) : (
      <p className="muted-text">No data available.</p>
    )}
  </div>
);

const AIInsightsCard = ({ aiInsights }) => {
  if (!aiInsights) return null;
  return (
    <div className="card">
      <div className="card-title-wrap">
        <h2>AI Summary & Resume Guidance</h2>
        <p className="card-subtext">Smart analysis generated by AI for your resume.</p>
      </div>
      <div className="summary-highlight">
        <h3>AI Summary</h3>
        <p>{aiInsights.aiSummary || "No summary available."}</p>
      </div>
      <div className="ai-grid">
        <ListSection title="AI Suggestions"          items={aiInsights.aiSuggestions}         icon="✦" />
        <ListSection title="Improved Project Bullets" items={aiInsights.improvedProjectBullets} icon="→" />
      </div>
    </div>
  );
};

export default AIInsightsCard;